# Generated by Django 5.1.6 on 2025-08-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_customeraddress_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(db_index=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
