# Generated by Django 5.1.6 on 2025-08-05 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0016_product_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('ONLINE', 'Online Payment')], default='COD', help_text='Method of payment for the order.', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who placed this order.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_code',
            field=models.CharField(db_index=True, help_text='Unique 11-character alphanumeric code for the cart.', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the cart was created.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the cart was last updated.'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user to whom this cart belongs (can be null for anonymous carts).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='The cart to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='apiApp.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='The product added to the cart.', on_delete=django.db.models.deletion.CASCADE, related_name='item', to='apiApp.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='The quantity of the product in the cart.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, help_text='Optional image for the category.', null=True, upload_to='category_img'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the product category.', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier for the category.', unique=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, help_text='City.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(help_text='The customer to whom this address belongs.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number associated with the address.', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, help_text='State or province.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, help_text='Street address.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text="Required. User's email address, must be unique.", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture_url',
            field=models.URLField(blank=True, help_text="Optional URL for the user's profile picture.", null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount of the order.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the order was created.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(help_text="Currency of the order (e.g., 'usd').", max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(db_index=True, help_text='Email of the customer who placed the order.', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending Delivery', 'Pending Delivery'), ('Processing', 'Processing'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Pending Delivery', help_text="Current status of the order (e.g., 'Pending Delivery', 'Paid').", max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_checkout_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID from Stripe Checkout Session (optional, for online payments).', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(help_text='The order to which this item belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='apiApp.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(help_text='The product included in the order.', on_delete=django.db.models.deletion.CASCADE, to='apiApp.product'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, help_text='The quantity of the product in the order.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text='The category to which the product belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='apiApp.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(help_text='Detailed description of the product.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, help_text='Indicates if the product is featured.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the product.', null=True, upload_to='product_img'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Name of the product.', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the product.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly unique identifier for the product.', unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Current stock quantity of the product.'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='The calculated average rating for the product.'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.OneToOneField(help_text='The product for which this rating applies.', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='apiApp.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0, help_text='The total number of reviews for the product.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the review was created.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(help_text='The product being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='apiApp.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='The rating given to the product (1-5).'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(help_text='The text content of the review.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the review was last updated.'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(help_text='The user who submitted the review.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was added to the wishlist.'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(help_text='The product added to the wishlist.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='apiApp.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(help_text='The user who owns this wishlist entry.', on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL),
        ),
    ]
